name: Test Checkout

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: actions ls2
        uses: actions/checkout@v3
      - name: list dir
        run: ls
